const itemsData = [
	{
		id: 0,
		name: "Apple pencil",
		surname: "applepencil",
		price: "59.99",
		desc: "Like new apple pencil, second generation, ",
		category: "tech",
		condition: "Like-New",
		seller: "mock_user1",
		date: "10/22/2024",
		cover: "/listingImages/applePencil.png",
		footage: ["/listingImages/applePencil.png", "/listingImages/applePencilSlide1.png"],
	},
	{
		id: 1,
		name: "Ugg boots",
		surname: "uggboots",
		price: "100.00",
		desc: "Brand new ugg minis, size 8, no flaws, open to trades, size 8",
		category: "apparel",
		condition: "New",
		seller: "mock_user2",
		date: "10/22/2024",
		cover: "/listingImages/uggCover.png",
		footage: ["/listingImages/uggCover.png", "/listingImages/uggSlide1.png"],
	},
	{
		id: 2,
		name: "WhirlPool Microwave",
		surname: "whirlpoolmicrowave",
		price: "75.00",
		desc: "Lightly used microwave, in working condition, from best buy ",
		category: "appliances",
		condition: "Like-New",
		seller: "mock_user2",
		date: "10/22/2024",
		cover: "/listingImages/microwaveCover.png",
		footage: ["/listingImages/microwaveCover.png", "/listingImages/microwaveSlide1.png"],
	},
	{
		id: 3,
		name: "Hair dryer",
		surname: "hairdryer",
		price: "9.99",
		desc: "heavily used hair dryer, the handle gets hot sometimes",
		category: "appliances",
		condition: "Used",
		seller: "mock_user3",
		date: "10/24/2024",
		cover: "/listingImages/hairdryer.jpg",
		footage: ["/listingImages/hairdryer.jpg", "/listingImages/hairdryer2.jpg"],
	},
	{
		id: 4,
		name: "Broom",
		surname: "broom",
		price: "1000.00",
		desc: "Broom. Very used.",
		category: "appliances",
		condition: "Used",
		seller: "mock_user4",
		date: "10/22/2024",
		cover: "/listingImages/broom.jpg",
		footage: ["/listingImages/broom.jpg", "/listingImages/broom2.jpg"],
	},
	{
		id: 5,
		name: "Hdmi Cable",
		surname: "hdmicable",
		price: "15.00",
		desc: "60 foot hdmi cable, never used",
		category: "tech",
		condition: "New",
		seller: "mock_user4",
		date: "10/22/2024",
		cover: "/listingImages/hdmicable.jpg",
		footage: ["/listingImages/hdmicable.jpg", "/listingImages/hdmicable2.jpg"],
	},
	{
		id: 6,
		name: "Design Pattern (Textbook)",
		surname: "textbookDesignPattern",
		price: "15.00",
		desc: "Hardcover, used",
		category: "academic",
		condition: "Used",
		seller: "uriri",
		date: "10/26/2024",
		cover: "/listingImages/designPatternBook.jpg",
		footage: ["/listingImages/designPatternBook.jpg"],
	},
	{
		id: 7,
		name: "Engineering A Compiler (Textbook)",
		surname: "textbookEngineeringCompiler",
		price: "85.00",
		desc: "Hardcover, used",
		category: "academic",

		condition: "Used",
		seller: "uriri",
		date: "10/26/2024",
		inCart: false,
		selected: false,
		isHovered: false,
		isLiked: false,
		cover: "/listingImages/engineeringCompilerTextbook.jpg",
		footage: ["/listingImages/engineeringCompilerTextbook.jpg"],
	},
	{
		id: 8,
		name: "Logitech MX Master 3S Wireless Mouse - Black",
		surname: "logitechMaster",
		price: "40.00",
		desc: "For Mac and Windows",
		category: "tech",
		condition: "Used",
		seller: "uriri",
		date: "10/26/2024",
		cover: "/listingImages/mouse0.jpg",
		footage: ["/listingImages/mouse0.jpg", "/listingImages/mouse1.jpg", "/listingImages/mouse2.jpg"],
	},
];

export default itemsData;
