@startchen "Student Marketplace"

title
Student Marketplace
- Group #5
- Members: Christian Dela Cruz, Xing-Wei Lee, Sophia Tang
- Manager: Mahika Arora
end title


entity User{
}

relationship "is a" as UserRelationship <<identifying>>{
}

entity Buyer <<weak>>{
}

entity Seller <<weak>>{
}

relationship "has" as USERHAS{
}

entity "UMass Login" as UserLoginUMass{
}

entity Profile{
}

entity UserSettings{
}

entity Theme{
}

entity WishList {
}

entity Item {
}

entity ItemDescription{
}

entity ItemImage{
}

entity ItemCategory{
}

entity TradeOffer{
}

entity ChatHistory{
}

entity ChatMessage{
}

entity ChatThreads{

}

User -1- UserRelationship

UserRelationship =1= Buyer
UserRelationship =1= Seller

User =1= USERHAS

Buyer =(0, N)= Item
Seller =(0, N)= Item

USERHAS =1= UserLoginUMass
USERHAS =1= ChatHistory
USERHAS =1= WishList

USERHAS =1= Profile

Profile =1= UserSettings
UserSettings =1= Theme

Item =1= ItemDescription
ItemDescription =(1, N)= ItemImage

Item =(0, N)= ItemCategory
Item =1= TradeOffer

ChatHistory =(0, N)= ChatMessage
ChatHistory =(0, N)= ChatThreads

@endchen
