const games = [
	{
		name: "Apple pencil",
		surname: "applepencil",
		price: "59.99",
		desc: "Like new apple pencil, second generation, ",
		link: "https://www.cyberpunk.net/",
		catergory: "tech",
		size: "NA",
		condition: "Like-new",
		seller: "mock_user1",
		date: "10/22/2024",
		inCart: false,
		selected: false,
		isHovered: false,
		isLiked: false,
		rating: 78,
		id: 0,
		cover: "/listingImages/applePencil.png",
		footage: [
			"/listingImages/applePencilSlide1.png",
		],
	},
	{
		name: "Ugg boots",
		surname: "uggboots",
		price: "100.00",
		desc: "Brand new ugg minis, size 8, no flaws, open to trades ",
		link: "https://www.cyberpunk.net/",
		catergory: "apparel",
		size: "8",
		condition: "New",
		seller: "mock_user2",
		date: "10/22/2024",
		inCart: false,
		selected: false,
		isHovered: false,
		isLiked: false,
		rating: 78,
		id: 0,
		cover: "/listingImages/uggCover.png",
		footage: [
			"/listingImages/uggSlide1.png",
		],
	},
	{
		name: "WhirlPool Microwave",
		surname: "microwave",
		price: "75.00",
		desc: "Lightly used microwave, in working condition, from best buy ",
		link: "https://www.cyberpunk.net/",
		catergory: "appliances",
		size: "na",
		condition: "Like-New",
		seller: "mock_user2",
		date: "10/22/2024",
		inCart: false,
		selected: false,
		isHovered: false,
		isLiked: false,
		rating: 78,
		id: 0,
		cover: "/listingImages/microwaveCover.png",
		footage: [
			"/listingImages/microwaveSlide1.png",
		],
	},
	{
		name: "Hair dryer",
		surname: "hairdryer",
		price: "9.99",
		desc: "heavily used hair dryer, the handle gets hot sometimes",
		link: "https://www.cyberpunk.net/",
		catergory: "appliances",
		size: "NA",
		condition: "Used",
		seller: "mock_user3",
		date: "10/24/2024",
		inCart: false,
		selected: false,
		isHovered: false,
		isLiked: false,
		rating: 78,
		id: 0,
		cover: "/listingImages/hairdryer.jpg",
		footage: [
			"/listingImages/hairdryer2.jpg",
		],
	},
	{
		name: "Broom",
		surname: "broom",
		price: "1000.00",
		desc: "Broom. Very used.",
		link: "https://www.cyberpunk.net/",
		catergory: "appliances",
		size: "NA",
		condition: "Used",
		seller: "mock_user4",
		date: "10/22/2024",
		inCart: false,
		selected: false,
		isHovered: false,
		isLiked: false,
		rating: 78,
		id: 0,
		cover: "/listingImages/broom.png",
		footage: [
			"/listingImages/broom2.png",
		],
	},
	{
		name: "Hdmi Cable",
		surname: "hdmicable",
		price: "15.00",
		desc: "60 foot hdmi cable, never used",
		link: "https://www.cyberpunk.net/",
		catergory: "tech",
		size: "NA",
		condition: "New",
		seller: "mock_user4",
		date: "10/22/2024",
		inCart: false,
		selected: false,
		isHovered: false,
		isLiked: false,
		rating: 78,
		id: 0,
		cover: "/listingImages/hdmicable.png",
		footage: [
			"/listingImages/hdmicable2.png",
		],
	}
	
];

export default games;
